apiVersion: apps/v1
kind: Deployment

metadata:
  name: myapp-deployment
  labels:
    app: nginx
    tier: frontend

spec:
  selector:
    matchLabels:
      tier: frontend
  replicas: 3

  template:
    metadata:
      name: nginx-test
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
        - name: nginx-name
          image: nginx:1.18
